import wpsClient from '../../assets/cases/wps/history-2026-05/2026-05-24-japan-progress.png'
import excelHome from '../../assets/screenshots/web-excel/06-六方案卡片索引-细节.png'
import projectMapDeckgl from '../../assets/presentation/42/source/p02-project-map-deckgl.png'
import aircraft from '../../assets/screenshots/aircraft-modeling/08-Blender标定渲染-747四分之三视角.png'
import diceEarly from '../../assets/presentation/42/source/p21-dice-early.png'
import microsoftWordApi from '../../assets/presentation/42/web/p06-microsoft-word-api.png'
import wpsAddinOverview from '../../assets/presentation/42/web/p06-wps-addin-overview.png'
import sfCargoChart from '../../assets/presentation/42/web/sf-b747-cargo-position-chart.png'
import cargoDimensions from '../../assets/presentation/42/web/ckair-b747-dimensions.png'
import cargoContours from '../../assets/presentation/42/web/ckair-b747-contours.png'
import cargoManual from '../../assets/presentation/42/web/b747-cargo-manual-page-16.png'
import cbaResult from '../../assets/screenshots/cba-demo-3d/05-自动试排完成.png'
import diceLatest from '../../assets/presentation/42/source/p21-dice-latest.png'
import echartsSix from '../../assets/presentation/42/source/echarts-html-6.0.0.png'
import echartsFourDefault from '../../assets/presentation/42/source/echarts-default-4.9.0.png'
import echartsSixDefault from '../../assets/presentation/42/source/echarts-default-6.0.0.png'

export const media = { wpsClient, excelHome, projectMapDeckgl, aircraft, diceEarly, microsoftWordApi, wpsAddinOverview, sfCargoChart, cargoDimensions, cargoContours, cargoManual, cbaResult, diceLatest, echartsSix, echartsFourDefault, echartsSixDefault }
