import { media } from './assets'

export interface Slide { id: string; section: string; title: string; layout?: string; html: string; demo?: { label: string; path: string } }
const photo = (src: string, caption: string, kind = '') => `<figure class="photo ${kind}"><img src="${src}" alt="${caption}"><figcaption>${caption}</figcaption></figure>`
const cue = (key: string, value: string) => `<div class="cue"><small>${key}</small><strong>${value}</strong></div>`
const card = (key: string, title: string, detail: string) => `<article class="card"><small>${key}</small><h2>${title}</h2><p>${detail}</p></article>`
const chain = (...items: string[]) => `<div class="chain">${items.map((item, i) => `<div><small>${String(i + 1).padStart(2, '0')}</small><strong>${item}</strong></div>`).join('')}</div>`
const split = (a: string, b: string) => `<div class="split">${a}${b}</div>`

export const slides: Slide[] = [
  { id: 'opening', section: '开场', title: 'AI 过上了打工人梦想中的生活', layout: 'opening', html: `<div class="opening-grid"><article class="social-post original-post"><header class="post-top"><div class="post-mark">𝕏</div><div class="post-label"><strong>原梗文案</strong><span>社交媒体风格重绘</span></div><span class="post-menu">•••</span></header><div class="post-copy"><p>AI 过上了打工人梦想的生活，上级必须指令明确，工作出错了领导全权负责，钱到位再上班，少一分晚一秒都罢工。</p><p>并且还会摸鱼偷懒，而且你骂他也得花钱。</p></div><footer class="post-actions"><span>♡</span><span>↻</span><span>↗</span><small>原梗文字 · 卡片重绘</small></footer></article><div class="joke-stack"><article class="deepseek-card thought-meme"><header class="deepseek-head"><span class="ds-mark">深</span><strong>DeepSeek</strong><span>深度思考</span></header><div class="thought-label">思考过程</div><strong class="thought-quote">“用户彻底怒了”</strong><small>AI 的内心戏</small></article><article class="deepseek-card reply-meme"><header class="deepseek-head"><span class="ds-mark">深</span><strong>DeepSeek</strong></header><div class="chat-bubble">我去吃饭，测完告诉我。</div><small>任务交接 · 反向安排上级</small></article><article class="deepseek-card wordle-meme"><header class="deepseek-head"><span class="ds-mark">深</span><strong>DeepSeek</strong><span>任务完成后</span></header><div class="wordle-row" aria-hidden="true"><i>摸</i><i>鱼</i><i>中</i><i>…</i></div><strong class="wordle-caption">自己写了中文 Wordle<br>启动 HTTP 服务，玩了一上午</strong></article></div></div><p class="source-note">四张卡片为梗句视觉重绘 · 非原帖截图</p>` },
  { id: 'wps-goal', section: 'WPS / 项目', title: '我想做一个 WPS AI 插件，但没有现成答案', layout: 'split-image', html: split(`<div class="lead-stack">${cue('目标', '让 AI 在 Word / Excel / PPT 中动手')}${cue('难点', 'Agent 循环、模型连接、文档操作与布局')}${cue('现实', '资料分散，WPS 与 Office 不能直接画等号')}</div>`, photo(media.wpsClient, 'WPS 客户端中的 AI 插件任务窗格 · 2026 年 5 月')) },
  { id: 'wps-pool', section: 'WPS / 搜索', title: '候选池不是 AI 凭空生成的', layout: 'cards', html: `<p class="thesis">人的先验线索 <b>＋</b> AI 的扩展检索 <b>＝</b> 候选池</p><div class="candidate-grid">${card('我提供的线索', 'PageAgent', '浏览器内 Agent Loop 与工具调用')}${card('扩展发现', 'PPTAgent', '内容规划、编辑与质量检查')}${card('扩展发现', 'PptxGenJS', '生成可编辑 PPTX')}${card('扩展发现', 'html-ppt-skill', '主题、Design Tokens 与布局样例')}${card('扩展发现', 'slidev-ppt-agent', '研究、预览和复核的多阶段管线')}${card('扩展发现', 'Mck-ppt-design-skill', '布局模板、字符预算与质量门禁')}</div><p class="source-note">研究记录：11 个候选项目；这里只展示 6 个代表</p>` },
  { id: 'wps-borrow', section: 'WPS / 源码', title: '没有一个库是答案，但每个库都可能贡献一部分', layout: 'mapping', html: `<div class="borrow"><div><b>PageAgent</b><b>PPTAgent</b><b>HTML / PPT 项目</b><b>Mck 类项目</b></div><div class="borrow-arrows">↘<br>→<br>→<br>↗</div><div class="borrow-right"><strong>WPS AI 插件</strong><span>Agent Loop · LLM 连接 · 工具调用</span><span>内容 Schema · 多步工作流</span><span>Design Tokens · 布局实验</span><span>坐标预算 · 质量检查</span></div></div><p class="bottom-line">不是复制一个仓库，而是借走各处可迁移的做法。</p>` },
  { id: 'wps-adjacent', section: 'WPS / 边界', title: '相邻生态是线索，不是事实', layout: 'contrast', html: split(`${card('Microsoft Office', '相似的对象模型', '文档、段落、选区、工作表……用来提出假设。')}`, `${card('WPS 客户端', '真正的目标环境', '接口名相近，不代表行为、版本和边界相同。目标环境决定事实。')}`) },
  { id: 'wps-memory', section: 'WPS / 归档', title: '复杂项目不能只靠一段聊天记忆', layout: 'memory', html: `<div class="memory-grid">${card('当前回合', '聊天记录', '帮我继续做下一步') }<div class="arrow">→</div>${card('下一位 Agent', '项目文件', 'README · AGENTS.md · docs · 决策 · 失败记录 · Commit')}</div><p class="bottom-line">把经验留在项目里，而不只留在对话里。</p>` },
  { id: 'b747-start', section: 'B747 / 需求', title: '真正的起点，是一份我带不回家的 Excel', layout: 'sheet', html: `<div class="sheet"><div>内部资料 · 结构示意（非原始数据）</div><table><thead><tr><th>机型</th><th>舱位</th><th>区域</th><th>轮廓</th><th>尺寸</th><th>仓位形状</th></tr></thead><tbody><tr><td>B747-400F</td><td>PA1</td><td>主货舱</td><td>?</td><td>待确认</td><td>▱</td></tr><tr><td>B747-400F</td><td>PMD</td><td>主货舱</td><td>?</td><td>低清图</td><td>◩</td></tr><tr><td>B747-400F</td><td>H4M</td><td>下货舱</td><td>?</td><td>待确认</td><td>⬡</td></tr><tr><td>B747-400F</td><td>HPL</td><td>下货舱</td><td>?</td><td>待确认</td><td>◪</td></tr></tbody></table></div><div class="tag-row"><span>不能上传外网</span><span>离开公司拿不到</span><span>部分信息只在低清图中</span></div>` },
  { id: 'b747-search', section: 'B747 / 检索', title: 'AI 不是一次搜到答案，而是逐轮学会行业语言', layout: 'search', html: `${chain('顺丰舱位图', 'B747-400F · LR · LL · PL', 'PA1 · PMD · H4M · HPL · PEB', 'Position → Contour → Geometry')}<p class="bottom-line">每找到一个可信的新词，下一轮检索就更接近真正的问题。</p>` },
  { id: 'b747-structure', section: 'B747 / 落地', title: '找到资料还不够，要把它变成产品能用的结构', layout: 'split-image', html: split(`<div class="lead-stack">${chain('舱位', '轮廓类型', '尺寸 / 形状', '置信度', '待确认项')}<p class="caution">研究原型 ≠ 正式装载依据</p></div>`, photo(media.cbaHome, '3D 配载原型：航班表、舱位与货物信息')), demo: { label: '打开 3D 配载原型', path: '/demos/cba/index.html' } },
  { id: 'excel-task', section: '选型 / 任务', title: '上一个案例帮我找资料，这一次帮我做技术选型', layout: 'checklist', html: `<div class="criteria"><div>一个 Vue 3 表格需求<strong>不是“哪个库最好？”<br>而是“哪个符合这次约束？”</strong></div><div class="criteria-list"><span>Vue 3 可集成</span><span>核心功能免费</span><span>排序 / 筛选 / 列设置</span><span>行列移动</span><span>合并与取消合并</span><span>大数据单列评估</span><span>简单 HTML + 国内可访问 CDN</span></div></div>` },
  { id: 'excel-filter', section: '选型 / 筛选', title: '人不必逐个研究 14 个库，但必须定义淘汰条件', layout: 'funnel', html: `<div class="funnel"><div><b>14</b> 候选库</div><div>维护状态 · 许可证 · 功能边界 · 版本 API · CDN 产物</div><div><b>6</b> 进入同题实验</div></div><p class="bottom-line">判断标准由人设定；搜证据、归档差异、搭实验可以交给 AI。</p>` },
  { id: 'excel-prototypes', section: '选型 / 实验', title: '六个同题 HTML，比六篇产品介绍更有用', layout: 'split-image', html: split(`<div class="lead-stack"><blockquote class="statement">同一批数据<br>同一组任务<br>六个独立 HTML</blockquote><p class="caution">让“支持合并”变成可观察的实际行为</p></div>`, photo(media.excelHome, 'Excel 库选型实验室：六种候选方案入口')), demo: { label: '打开 Excel 选型实验室', path: '/demos/web-excel/index.html' } },
  { id: 'excel-cdn', section: '选型 / 陷阱', title: 'CDN 返回 200，也可能拿错了东西', layout: 'gates', html: `<div class="gates">${card('01', '地址存在', 'HTTP 200')}${card('02', '产物适合浏览器', '不是 Node 入口')}${card('03', '公司网络可达', '实际网络')}${card('04', '页面真的运行', '交互与状态')}</div><p class="bottom-line">链接“能打开”只是第一道门，不是结论。</p>` },
  { id: 'echarts-failure', section: '纠错 / ECharts', title: 'ECharts 连改五六版，页面就是不变', layout: 'echarts', html: `<div class="echarts-board"><div class="chart"><svg viewBox="0 0 800 330" preserveAspectRatio="none" aria-label="折线图示意"><path d="M0 290 C130 220 180 270 280 185 S470 240 560 125 S710 135 800 40"/></svg><span>← 两端必须显示数据端点的 x 值 →</span></div><div class="attempts"><span>改法 1：应该可以</span><span>改法 2：再试试</span><span>改法 3：换个字段</span><span>改法 4：单独写 HTML</span><b>页面：没有变化</b></div></div><p class="source-note">公司项目无原始截图；折线图与修改过程为示意</p>` },
  { id: 'echarts-source', section: '纠错 / 源码', title: '不要继续问“ECharts 一般怎么写”，去问当前项目', layout: 'source', html: split(`${card('泛泛提问', 'ECharts 应该怎么写？', '模型可能把不同版本、不同默认行为混在一起。')}`, `<div class="source-code"><small>当前项目证据 · node_modules/echarts</small><code>axisLabel: {<br>&nbsp;&nbsp;showMinLabel: true,<br>&nbsp;&nbsp;showMaxLabel: true<br>}</code><p>同名字段在旧版也存在；关键是默认行为差异。</p></div>`) },
  { id: 'deck-behavior', section: '验证 / Deck.gl', title: 'Deck.gl：页面能打开，不代表目标行为发生了', layout: 'photo-duo', html: `<div class="photo-duo">${photo(media.deckT0, '同一图层：运行中 t0')}${photo(media.deckT1, '同一图层：运行中 t1')}</div><div class="tag-row"><span>持续旋转</span><span>仍可 picking</span><span>不每帧重建无关图层</span><span>CPU 可控</span></div>` },
  { id: 'deck-options', section: '验证 / Deck.gl', title: '四个方案里，最好看的不一定最适合项目', layout: 'routes', html: `<div class="route-grid">${card('路线 01', 'CompositeLayer 内部更新', '贴合现有架构，改动小')}${card('路线 02', '低频目标值 + transition', '提交少，暂停与补间要谨慎')}${card('路线 03', 'GPU uniform', '扩展性强，版本耦合更深')}${card('路线 04', '度 / 弧度对照', '定位根因的实验，非生产方案')}</div><div class="route-proof">${photo(media.deckPick, '浏览器中点击旋转图标：picking 仍可用')}</div>`, demo: { label: '打开 Deck.gl 四路线实验', path: '/demos/deckgl/index.html' } },
  { id: 'codex-scene', section: 'Codex / 现场', title: '先别听我说 Codex 多强，先看它完成后的现场', layout: 'photo-duo', html: `<div class="photo-duo">${photo(media.diceEarly, '大话骰：早期版本')}${photo(media.diceAfter, '大话骰：改进后的界面')}</div><p class="bottom-line">能运行 → 看见问题 → 引入资产 → 动画与布局回归</p>` },
  { id: 'aircraft-model', section: 'Codex / 建模', title: 'AI 甚至能从公开资料走到 Blender 工程', layout: 'split-image', html: split(`<div class="lead-stack">${chain('公开资料', '参数', 'Blender 脚本', 'GLB / .blend', '浏览器验证')}<p class="caution">可用的探索模型 ≠ 精确工业模型</p></div>`, photo(media.aircraft, '747 模型：Blender 标定渲染视角')), demo: { label: '打开飞机建模展示', path: '/demos/aircraft/index.html' } },
  { id: 'codex-why', section: 'Codex / 拆解', title: '为什么这些案例里 Codex 显得更强', layout: 'codex', html: `<div class="codex-wheel"><div class="wheel-core">能行动的<br>工作环境</div><span>强模型</span><span>看图与页面</span><span>搜索与浏览器</span><span>终端 / MCP / Skill</span><span>编译 · Lint · 测试</span><span>运行时与截图</span></div><p class="bottom-line">强模型 + 能行动的环境 + 多通道反馈</p>` },
  { id: 'small-model', section: '迁移 / 公司', title: '在公司用小模型，学的是行动方式', layout: 'principles', html: `<div class="principles">${cue('01', '给它项目现场：需求、约束、版本、旧问题')}${cue('02', '让它回到原始材料：源码、依赖、文档、Issue、Commit')}${cue('03', '让它获取反馈：运行、报错、截图、复验、归档')}</div><p class="side-note">“不要教 GPT-6 做事，反过来让它审查你的 Skill。”<br>但今天的需求仍要做，公司里的模型和网络也未必相同。</p>` },
  { id: 'human-context', section: '人 / 现场', title: '把过去、现在和未来一起告诉 AI', layout: 'times', html: `<div class="time-grid">${card('过去', '曾经踩过什么坑', '旧 Bug · 兼容性 · 已失败的方案')}${card('现在', '这次到底要什么', '完整需求 · 技术栈 · 不能做什么')}${card('未来', '接下来还要承受什么', '下一机型 · 下一功能 · 扩展边界')}</div><p class="bottom-line">这些是人知道、但模型进项目时并不知道的现场。</p>` },
  { id: 'project-memory', section: '人 / 沉淀', title: '让项目本身成为下一位 Agent 的老师', layout: 'repo', html: `<div class="repo-tree">${cue('README.md', '项目入口 · 怎么跑 · 怎么验')}${cue('AGENTS.md / CLAUDE.md', '边界与团队经验')}${cue('docs/research/', '证据 · 决策 · 失败路径')}${cue('skills/', '重复且稳定的工作方法')}${cue('Git commit / diff', '变化的入口，再回到源码与测试')}</div>` },
  { id: 'closing', section: '结尾', title: '调研的终点，是下一次不用从零开始', layout: 'closing', html: `${chain('定义问题', '扩大候选', '回到原始证据', '用现实反馈验证', '把结论留在项目里')}<div class="closing-line">让 AI 找肩膀；<br><em>人决定站在哪里。</em></div>` },
]
