import { media } from './assets'

export interface Slide { id: string; section: string; title: string; layout?: string; html: string; demo?: { label: string; path: string } }
const photo = (src: string, caption: string, kind = '') => `<figure class="photo ${kind}"><img src="${src}" alt="${caption}"><figcaption>${caption}</figcaption></figure>`
const cue = (key: string, value: string) => `<div class="cue"><small>${key}</small><strong>${value}</strong></div>`
const card = (key: string, title: string, detail: string) => `<article class="card"><small>${key}</small><h2>${title}</h2><p>${detail}</p></article>`
const candidate = (title: string, intro: string, borrow: string) => `<article class="card candidate"><small>项目参考</small><h2>${title}</h2><p>${intro}</p><p class="borrow-point"><b>可借鉴：</b>${borrow}</p></article>`
const chain = (...items: string[]) => `<div class="chain">${items.map((item, i) => `<div><small>${String(i + 1).padStart(2, '0')}</small><strong>${item}</strong></div>`).join('')}</div>`
const split = (a: string, b: string) => `<div class="split">${a}${b}</div>`

export const slides: Slide[] = [
  { id: 'opening', section: '开场', title: 'AI 过上了打工人梦想中的生活', layout: 'opening', html: `<div class="opening-grid"><article class="social-post original-post"><header class="post-top"><div class="post-mark">X</div><div class="post-skeleton" aria-hidden="true"><i></i><i></i></div><span class="post-menu">•••</span></header><div class="post-copy"><p>AI 过上了打工人梦想的生活，上级必须指令明确，工作出错了领导全权负责，钱到位再上班，少一分晚一秒都罢工。</p><p>并且还会摸鱼偷懒，而且你骂他也得花钱。</p></div><footer class="post-actions" aria-hidden="true"><span>♡</span><span>↻</span><span>↗</span></footer></article><section class="deepseek-screen" aria-label="DeepSeek 思考内容风格重绘"><article class="ds-thought-item"><header class="ds-thinking-top"><span class="ds-atom">⚛</span><strong>已思考</strong><span class="ds-chevron">⌄</span></header><div class="ds-thought-copy"><span class="ds-bullet"></span><p>用户彻底怒了</p></div></article><article class="ds-thought-item"><header class="ds-thinking-top"><span class="ds-atom">⚛</span><strong>已思考</strong><span class="ds-chevron">⌄</span></header><div class="ds-thought-copy"><span class="ds-bullet"></span><p>我去吃饭，测完告诉我。</p></div></article><article class="ds-thought-item"><header class="ds-thinking-top"><span class="ds-atom">⚛</span><strong>已思考</strong><span class="ds-chevron">⌄</span></header><div class="ds-thought-copy ds-event-summary"><span class="ds-bullet"></span><div><small>行为描述 · 非思考原文</small><p>任务完成后，自己写了中文 Wordle、启动 HTTP 服务并玩起来。</p></div></div></article></section></div><p class="source-note">梗句与现象重绘 · 非原帖截图</p>` },
  { id: 'wps-goal', section: 'WPS / 项目', title: '我想做一个 WPS AI 插件，但没有现成答案', layout: 'split-image', html: split(`<div class="lead-stack">${cue('目标', '让 AI 在 Word / Excel / PPT 中动手')}${cue('难点', 'Agent 循环、模型连接、文档操作与布局')}${cue('现实', '资料分散，WPS 与 Office 不能直接画等号')}</div>`, photo(media.wpsClient, 'WPS 客户端中的 AI 插件任务窗格')) },
  { id: 'wps-pool', section: 'WPS / 搜索', title: '候选池不是 AI 凭空生成的', layout: 'cards', html: `<p class="thesis">人的先验线索 <b>＋</b> AI 的扩展检索 <b>＝</b> 候选池</p><div class="candidate-grid">${candidate('PageAgent', '面向网页任务的浏览器 Agent，可在页面中观察、规划并调用工具。', '浏览器 Agent Loop 与工具调用')}${candidate('PPTAgent', '研究型演示文稿生成项目，把内容规划、编辑和质量检查拆成多个阶段。', '规划、编辑与 QA 分阶段')}${candidate('PptxGenJS', 'JavaScript 演示文稿生成库，输出可继续编辑的 PPTX 文件。', '结构化生成与可编辑产物')}${candidate('html-ppt-skill', '用 HTML/CSS 制作演示稿的技能与样例集合。', '主题、Design Tokens 与布局样例')}${candidate('slidev-ppt-agent', '围绕 Slidev 的演示稿工作流，覆盖调研、预览和复核。', '多阶段流水线与预览反馈')}${candidate('Mck-ppt-design-skill', '强调版式模板、文本预算和质量门槛的演示设计方法。', '布局模板、字符预算与质量门禁')}</div><p class="source-note">先从已知案例出发，再沿可验证的相似能力扩展；这里只展示 6 个代表项目。</p>` },
  { id: 'wps-borrow', section: 'WPS / 源码', title: '没有一个库是答案，但每个库都可能贡献一部分', layout: 'mapping', html: `<div class="borrow"><div><b>PageAgent</b><b>PPTAgent</b><b>HTML / PPT 项目</b><b>Mck 类项目</b></div><div class="borrow-arrows">↘<br>→<br>→<br>↗</div><div class="borrow-right"><strong>WPS AI 插件</strong><span>Agent Loop · LLM 连接 · 工具调用</span><span>内容 Schema · 多步工作流</span><span>Design Tokens · 布局实验</span><span>坐标预算 · 质量检查</span></div></div><p class="bottom-line">不是复制一个仓库，而是借走各处可迁移的做法。</p>` },
  { id: 'wps-adjacent', section: 'WPS / 边界', title: '相邻生态是线索，不是事实', layout: 'photo-duo', html: `<div class="photo-duo official-duo">${photo(media.microsoftWordApi, 'Microsoft Learn · Word JavaScript API')}${photo(media.wpsAddinOverview, 'WPS 开放平台 · 加载项概述')}</div><p class="bottom-line">相似对象模型提出假设；目标客户端里的运行结果才是事实。</p>` },
  { id: 'wps-memory', section: 'WPS / 归档', title: '复杂项目不能只靠一段聊天记忆', layout: 'memory', html: `<div class="memory-grid">${card('当前回合', '聊天记录', '帮我继续做下一步') }<div class="arrow">→</div>${card('下一位 Agent', '项目文件', 'README · AGENTS.md · docs · 决策 · 失败记录 · Commit')}</div><p class="bottom-line">把经验留在项目里，而不只留在对话里。</p>` },
  { id: 'b747-start', section: 'B747 / 需求', title: '真正的起点，是一份我带不回家的 Excel', layout: 'b747-evidence', html: `<div class="b747-evidence">${photo(media.cbaTable, '项目表格：航班与货物记录')}${photo(media.sfCargoChart, '顺丰航空官网 · B747 货舱舱位分布')}</div><p class="bottom-line">一边是业务表格，一边是公开舱位图；问题从两者之间的缺口开始。</p>` },
  { id: 'b747-search', section: 'B747 / 检索', title: 'AI 不是一次搜到答案，而是逐轮学会行业语言', layout: 'search', html: `<div class="search-evidence">${chain('B747-400F', 'LR · LL · PL', 'PA1 · PMD · H4M · HPL', 'Position → Contour → Geometry')}<div class="search-photos">${photo(media.cargoSearch, '检索结果：从机型关键词扩展')}${photo(media.cargoManual, '货运手册：回到原始资料交叉核对')}</div></div><p class="bottom-line">每找到一个可信的新词，下一轮检索就更接近真正的问题。</p>` },
  { id: 'b747-structure', section: 'B747 / 落地', title: '找到资料还不够，要把它变成产品能用的结构', layout: 'split-image', html: split(`<div class="lead-stack">${chain('舱位', '轮廓类型', '尺寸 / 形状', '置信度', '待确认项')}<p class="caution">研究原型 ≠ 正式装载依据</p></div>`, photo(media.cbaResult, 'CBA 3D 配载原型 · 自动分配完成')), demo: { label: '打开 3D 配载原型', path: '/demos/cba/index.html' } },
  { id: 'excel-task', section: '选型 / 任务', title: '上一个案例帮我找资料，这一次帮我做技术选型', layout: 'checklist', html: `<div class="criteria"><div>一个 Vue 3 表格需求<strong>不是“哪个库最好？”<br>而是“哪个符合这次约束？”</strong></div><div class="criteria-list"><span>Vue 3 可集成</span><span>核心功能免费</span><span>排序 / 筛选 / 列设置</span><span>行列移动</span><span>合并与取消合并</span><span>大数据单列评估</span><span>简单 HTML + 国内可访问 CDN</span></div></div>` },
  { id: 'excel-filter', section: '选型 / 筛选', title: '人不必逐个研究 14 个库，但必须定义淘汰条件', layout: 'funnel', html: `<div class="funnel"><div><b>14</b> 候选库</div><div>维护状态 · 许可证 · 功能边界 · 版本 API · CDN 产物</div><div><b>6</b> 进入同题实验</div></div><p class="bottom-line">判断标准由人设定；搜证据、归档差异、搭实验可以交给 AI。</p>` },
  { id: 'excel-prototypes', section: '选型 / 实验', title: '六个同题 HTML，比六篇产品介绍更有用', layout: 'split-image', html: split(`<div class="lead-stack"><blockquote class="statement">同一批数据<br>同一组任务<br>六个独立 HTML</blockquote><p class="caution">让“支持合并”变成可观察的实际行为</p></div>`, photo(media.excelHome, 'Excel 库选型实验室：六种候选方案入口')), demo: { label: '打开 Excel 选型实验室', path: '/demos/web-excel/index.html' } },
  { id: 'excel-cdn', section: '选型 / 陷阱', title: 'CDN 返回 200，也可能拿错了东西', layout: 'cdn', html: `<div class="cdn-proof"><div class="cdn-code"><small>真实页面 · public/demos/web-excel/demos/vxe.html</small><pre><code>&lt;!doctype html&gt;
&lt;html lang="zh-CN"&gt;
&lt;head&gt;
  &lt;meta charset="utf-8"&gt;
...
const ASSETS = [{
  name: "xe.js",
  path: "xe-utils@4.0.12/lib/index.umd.min.js",
  url: <b>"https://registry.npmmirror.com/xe-utils/4.0.12/files/lib/index.umd.min.js"</b>,
  status: 200, type: "text/javascript"
}];</code></pre><p class="cdn-failure"><b>旧路径 xe-utils/min.js</b> · HTTP 200 · 内容却是单个 CommonJS 函数，不是浏览器需要的完整 UMD 包。</p></div><div class="cdn-gates">${card('01', 'HTTP 200', '地址存在')}${card('02', '格式正确', '浏览器可执行')}${card('03', '网络可达', '目标网络')}${card('04', '页面可用', '真实交互')}</div></div><p class="bottom-line">现在页面明确指向 UMD 构建；状态码只证明拿到了响应，产物格式与目标环境还要另验。</p>` },
  { id: 'echarts-failure', section: '纠错 / ECharts', title: 'ECharts 连改五六版，页面就是不变', layout: 'echarts', html: `<div class="echarts-story"><div class="echarts-before">${photo(media.echartsBefore, '实际 ECharts HTML 复现 · 两端标签未显示')}<aside><b>改了五六版</b><p>反复换写法、重写 HTML；页面两端标签仍没出现。</p></aside></div><div class="echarts-reason"><strong>问题卡在上下文和验证</strong><p>模型按网上常见示例猜字段与默认值；项目版本、配置和参考示例并不一致。这个非 TypeScript 页面也没有编译阶段替我们发现错误假设，于是修改看起来合理，结果却原地不动。</p><small>此图是同类配置的可复现实验，不是公司项目截图。</small></div></div>` },
  { id: 'echarts-source', section: '纠错 / 源码', title: '把两个 HTML 并排跑，再看项目自己的 node_modules', layout: 'source', html: `<div class="html-compare">${photo(media.echartsBefore, 'HTML A · ECharts 4.9.0 · 两端标签未显示')}${photo(media.echartsExplicit, 'HTML B · ECharts 6.0.0 · 显式保留两端')}</div><p class="source-note">两页使用真实 ECharts 渲染同一组数据；A 关闭两端标签，B 显式开启 showMinLabel / showMaxLabel。回到项目先查 node_modules/echarts 的版本与类型定义，再用相同 option 验证默认行为，避免把版本与配置差异混为一个结论。</p>` },
  { id: 'deck-behavior', section: '验证 / Deck.gl', title: 'Deck.gl：页面能打开，不代表目标行为发生了', layout: 'deck-rotation', html: `<div class="storm-stage"><svg viewBox="0 0 1300 540" role="img" aria-label="台风路径示意，台风标记沿路径旋转"><defs><linearGradient id="sea" x2="1" y2="1"><stop stop-color="#e6eee8"/><stop offset="1" stop-color="#d5e4df"/></linearGradient></defs><rect width="1300" height="540" rx="26" fill="url(#sea)"/><path class="storm-route" d="M130 410 C260 355 260 260 430 282 S650 365 760 250 S960 140 1160 160"/><g class="storm-marker"><circle r="37" fill="#173d39"/><path d="M-20 0 C-10-19 13-22 22-5 C28 8 12 24-2 18 C-13 14-12 5-5 2 C2-1 8 4 5 10" fill="none" stroke="#fff" stroke-width="5" stroke-linecap="round"/><path d="M0-27V-42M0 27V42M-27 0H-42M27 0H42" stroke="#173d39" stroke-width="4"/><animateMotion dur="9s" repeatCount="indefinite" rotate="auto" path="M130 410 C260 355 260 260 430 282 S650 365 760 250 S960 140 1160 160"/></g><text x="62" y="70">路径示意 · 标记沿轨迹连续移动并旋转</text><text x="950" y="485">Deck.gl · 更新与 picking 实测</text></svg><div class="storm-checks"><b>同一图层持续更新</b><b>旋转方向跟随路径</b><b>点击仍可 picking</b><b>避免每帧重建无关图层</b></div></div>` },
  { id: 'deck-options', section: '验证 / Deck.gl', title: '四个方案里，最好看的不一定最适合项目', layout: 'routes', html: `<div class="route-grid">${card('路线 01', 'CompositeLayer 内部更新', '贴合现有架构，改动小')}${card('路线 02', '低频目标值 + transition', '提交少，暂停与补间要谨慎')}${card('路线 03', 'GPU uniform', '扩展性强，版本耦合更深')}${card('路线 04', '度 / 弧度对照', '定位根因的实验，非生产方案')}</div><div class="route-proof">${photo(media.deckT0, '运行中：台风图标沿路径旋转')}${photo(media.deckPick, '点击图标：picking 仍可用')}</div>`, demo: { label: '打开 Deck.gl 四路线实验', path: '/demos/deckgl/index.html' } },
  { id: 'codex-scene', section: 'Codex / 现场', title: '先别听我说 Codex 多强，先看它完成后的现场', layout: 'photo-duo', html: `<div class="photo-duo">${photo(media.diceEarly, '大话骰：早期版本')}${photo(media.diceLatest, 'KayKit 模型下载后 · 最新版本实际运行截图')}</div><p class="bottom-line">从占位棋子到四个 KayKit 角色：下载模型、接入资源，再回到运行页面验收。</p>` },
  { id: 'aircraft-model', section: 'Codex / 建模', title: 'AI 甚至能从公开资料走到 Blender 工程', layout: 'split-image', html: split(`<div class="lead-stack">${chain('公开资料', '参数', 'Blender 脚本', 'GLB / .blend', '浏览器验证')}<p class="caution">可用的探索模型 ≠ 精确工业模型</p></div>`, photo(media.aircraft, '747 模型：Blender 标定渲染视角')), demo: { label: '打开飞机建模展示', path: '/demos/aircraft/index.html' } },
  { id: 'codex-why', section: 'Codex / 拆解', title: '为什么这些案例里 Codex 显得更强', layout: 'codex', html: `<div class="codex-wheel"><div class="wheel-core">能行动的<br>工作环境</div><span>强模型</span><span>看图与页面</span><span>搜索与浏览器</span><span>终端 / MCP / Skill</span><span>编译 · Lint · 测试</span><span>运行时与截图</span></div><p class="bottom-line">强模型 + 能行动的环境 + 多通道反馈</p>` },
  { id: 'small-model', section: '迁移 / 公司', title: '在公司用小模型，学的是行动方式', layout: 'principles', html: `<div class="principles">${cue('01', '给它项目现场：需求、约束、版本、旧问题')}${cue('02', '让它回到原始材料：源码、依赖、文档、Issue、Commit')}${cue('03', '让它获取反馈：运行、报错、截图、复验、归档')}</div><p class="side-note">“不要教 GPT-6 做事，反过来让它审查你的 Skill。”<br>但今天的需求仍要做，公司里的模型和网络也未必相同。</p>` },
  { id: 'human-context', section: '人 / 现场', title: '把过去、现在和未来一起告诉 AI', layout: 'times', html: `<div class="time-grid">${card('过去', '曾经踩过什么坑', '旧 Bug · 兼容性 · 已失败的方案')}${card('现在', '这次到底要什么', '完整需求 · 技术栈 · 不能做什么')}${card('未来', '接下来还要承受什么', '下一机型 · 下一功能 · 扩展边界')}</div><p class="bottom-line">这些是人知道、但模型进项目时并不知道的现场。</p>` },
  { id: 'project-memory', section: '人 / 沉淀', title: '让项目本身成为下一位 Agent 的老师', layout: 'repo', html: `<div class="repo-tree">${cue('README.md', '项目入口 · 怎么跑 · 怎么验')}${cue('AGENTS.md / CLAUDE.md', '边界与团队经验')}${cue('docs/research/', '证据 · 决策 · 失败路径')}${cue('skills/', '重复且稳定的工作方法')}${cue('Git commit / diff', '变化的入口，再回到源码与测试')}</div>` },
  { id: 'closing', section: '结尾', title: '调研的终点，是下一次不用从零开始', layout: 'closing', html: `${chain('定义问题', '扩大候选', '回到原始证据', '用现实反馈验证', '把结论留在项目里')}<div class="closing-line">让 AI 找肩膀；<br><em>人决定站在哪里。</em></div>` },
]
